[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "franka_teleop"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9,<3.13"  
license = {text = "Apache-2.0"}
authors = [
    {name = "Runtian Xu", email = "xuruntian03@163.com"},
]

dependencies = [
    "absl-py>=2.3.1",
    "easyhid>=0.0.10",
    "flask>=2.0.0",
    "numpy>=1.26.4",
    "requests>=2.32.5",
    "scipy>=1.13.1",
]

[tool.setuptools.packages.find]
include = [
    "franka_robot_server",
    "franka_teleop",
]
